spring:
  application:
    name: hogarts-artifacts-online
  datasource:
    url: jdbc:h2:mem:hogwarts
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
   # database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
 # h2:
 #   console:
  #    enabled: true
   #   path: /h2-console
api:
  endpoint:
    base-url: /api/v1
server:
  port: 80
